# Scraping Google search results: AI Copyright & Governance

---
## 0. Install Dependencies

In [ ]:
!pip install google-search-results pandas python-dotenv requests trafilatura youtube_transcript_api

---
## 1. Imports & Configuration

In [16]:
from serpapi import GoogleSearch
from youtube_transcript_api import YouTubeTranscriptApi
from concurrent.futures import ThreadPoolExecutor, as_completed
import trafilatura
import pandas as pd
from dotenv import load_dotenv
import os
import re
import time

load_dotenv()
SERP_API_KEY = os.getenv("SERPAPI_KEY")

# Max number of articles to scrape
MAX_NUM_RESULTS = 10

---
## 2. SerpApi - Collecting article & video URLs

In [17]:
def collect_search_results(queries: list[str],
                           num_results: int = MAX_NUM_RESULTS) -> tuple[pd.DataFrame, list[dict]]:
    """
    Search Google for each query and collect:
    - organic_results  → articles (title, snippet, url, source, date)
    - inline_videos    → YouTube videos (title, channel, url)

    Returns:
        articles_df  : DataFrame of all article metadata
        raw_results  : list of raw SerpAPI result dicts (just for inspection)
    """
    article_rows = []
    video_rows   = []
    raw_results  = []

    for query in queries:
        print(f"\n🔍 Searching: '{query}'")

        params = {
            "engine":        "google",
            "q":             query,
            "google_domain": "google.com",
            "hl":            "en",
            "gl":            "us",
            "api_key":       SERP_API_KEY
        }

        search  = GoogleSearch(params)
        results = search.get_dict()
        raw_results.append({"query": query, "results": results})

        # ── Organic articles ──
        organic = results.get("organic_results", [])
        if not organic:
            print(f"  ⚠️  No organic_results for: {query}")
        else:
            for article in organic[:num_results]:
                article_rows.append({
                    "query":   query,
                    "title":   article.get("title"),
                    "snippet": article.get("snippet"),
                    "source":  article.get("source"),
                    "date":    article.get("date"),
                    "url":     article.get("link"),
                    "type":    "article"
                })
            print(f"  ✅ {len(organic[:num_results])} articles collected")

        # ── Inline videos ──
        videos = results.get("inline_videos", [])
        if videos:
            for video in videos:
                video_rows.append({
                    "query":   query,
                    "title":   video.get("title"),
                    "snippet": None,
                    "source":  video.get("channel"),
                    "date":    None,
                    "url":     video.get("link"),
                    "type":    "video"
                })
            print(f"  ✅ {len(videos)} videos collected")

    # Combine into single DataFrame
    all_rows = article_rows + video_rows
    df = pd.DataFrame(all_rows)

    if df.empty:
        print("\n⚠️  No results collected across all queries.")
        return df, raw_results

    # Remove duplicates by URL
    df = df.drop_duplicates(subset="url").reset_index(drop=True)

    return df, raw_results

In [18]:
# ── Collect urls from search query ──
df, raw = collect_search_results(["AI intellectual property", 
                                  "copyright Generative AI"])
df.head()

🔍 Searching: 'AI intellectual property'
  ✅ 10 articles collected

🔍 Searching: 'copyright Generative AI'
  ✅ 10 articles collected

,query,title,snippet,source,date,url,type
0,AI intellectual property,Generative AI: Navigating intellectual property,Fully AI-generated content is ineligible for c...,Nixon Peabody,"Sep 17, 2025",https://www.nixonpeabody.com/insights/articles...,article
1,AI intellectual property,Artificial Intelligence and Intellectual Property,AI inventions present the current patent syste...,World Intellectual Property Organization (WIPO),NaN,https://www.wipo.int/en/web/frontier-technolog...,article
2,AI intellectual property,"AI, Copyright, and the Law: The Ongoing Battle...","In the past year, courts, legislators, and reg...",University of Southern California,"Feb 4, 2025",https://sites.usc.edu/iptls/2025/02/04/ai-copy...,article
3,AI intellectual property,Copyright Or Copywrong? AI's Intellectual Prop...,The report states that AI-generated works need...,Forbes,"Feb 11, 2025",https://www.forbes.com/sites/douglaslaney/2025...,article
4,AI intellectual property,AI and intellectual property rights,AI tools are now increasingly being used for s...,Dentons,"Jan 28, 2025",https://www.dentons.com/en/insights/articles/2...,article

In [20]:
raw

[{'query': 'AI intellectual property',
  'results': {'search_metadata': {'id': '69ce4faf2771430db9186b92',
    'status': 'Success',
    'json_endpoint': 'https://serpapi.com/searches/G3XbEcf9TUuxjG1sMWYgSg/69ce4faf2771430db9186b92.json',
    'pixel_position_endpoint': 'https://serpapi.com/searches/G3XbEcf9TUuxjG1sMWYgSg/69ce4faf2771430db9186b92.json_with_pixel_position',
    'created_at': '2026-04-02 11:14:55 UTC',
    'processed_at': '2026-04-02 11:14:55 UTC',
    'google_url': 'https://www.google.com/search?q=AI+intellectual+property&oq=AI+intellectual+property&hl=en&gl=us&sourceid=chrome&ie=UTF-8',
    'raw_html_file': 'https://serpapi.com/searches/G3XbEcf9TUuxjG1sMWYgSg/69ce4faf2771430db9186b92.html',
    'total_time_taken': 0.7},
   'search_parameters': {'engine': 'google',
    'q': 'AI intellectual property',
    'google_domain': 'google.com',
    'hl': 'en',
    'gl': 'us',
    'device': 'desktop'},
   'search_information': {'query_displayed': 'AI intellectual property',
    'total_results': 135,
    'time_taken_displayed': 0.23,
    'organic_results_state': 'Results for exact spelling'},
   'ai_overview': {'page_token': 'Oy9lAXicxZbbkqo4FIbv5z2Gm70RbfHUVdRUQNR0i248tK03FMeIgihBI5f7Xeap5mkmoCK2Ys2eqqlJVUgCa2WtJF9-_fmn527Wf_0mLqNoi185jhBSQkGAPLtkBj6n43hjck7g4dBc_oE8YY8ZHOxD03YtwVyGgW8zS0-wN0x8EKqMiYUKY7sClrWh7kwWwGE7pGn-qO2qEVERk04naIaO7RWNdlxhTuPoY_17tU0HJVyyNyXP7MNVfMDqmJReypVWacjpPjUA_0FBUvIQaQUSgI8sZBW0SaG_TB0RbQPay14lXTFnBIGY2NAqqSrtSKhgNhGmk0ldMXHXGouDCpTC2PAaM_Gdp-vpgHmaA4RAund5GFi6PFGxzdXuNmHQOffa6JldmihdenaGUxoHic3Lp2QqcnZWs_FMvu7kGz2FoSL2JMgX5QfACIA5acdqExYu4lS2ZDe_xDUAARJnIUpYmTNC2lQ411yaaSfECXjSpFUOuvNgfAhG86b3MfX5rmg02PpQn3db2FA506B2XqBbtqUttfL3FHETZ4zjPONIt9RpQxTL8brUL4mVHODJ3sGbI0ighOqjRcinzZPzlgVFVE8OIp1JzRlKqAxMAPok2WRaKeldelDoJl46uAP8UtC1odU9v51e_MAtpOB0MnJ2P9At4CjXEiCjDBgIbi6hfLtaeZzgjtJYUhb5HB1J78mbdwCWly85huTcTU3uAEzMMobFrNteZ6mgNHuaEUmSkt5oTQKrqTE87fVUBDd5pOvJnesMiM3eiyyD-_LwsG9KoYBkBV1I_gJmHuiO5QTvreVeYvvaXISrKvsZrtk6a5UtcgY48I1fUGnz_0H8rOFqouEyfIi4-gxxquHqUw1HIK_h7lnDixCH8IuGkyeIQ3mdQ_z4RMMzxNE_QBwVIS49Qrxzj7hbgPgo0fAr4giNvmh4uvZTdjnEf13Dx_9Gw1Pi7VNzK-j7FSoU9t5g486crW_ZBPBRXNlO2NYnb8Wzqovuhd3xo1fd8r5rrvUqvrxFscXsBAC_uZvI9jzbjPa6920bBls7jGLG98JAKOt1KdjVXVIDx27tTd37IGQXg-Zmp7RMSTvsaofjuBW6x-060nv8kJR3Sl8zJvCt3qvLoYJ_DNjJqNVxDA_5-_aRNN4_FHT4GChDjx_GH2TRgT3Fma9fxGlbsbpNe2GMzYE62Q_9xXiizN2uV2eN1sFbkfBTqqRZYcFheQcYcvdoA8bXLWzT_25-aAqUBh6BgQpmKPlxYLCpazY-CHyzajhOw7CbtZpj2TzjoyjeCnyFwZtQqPwN5lT1Kw',
    'serpapi_link': 'https://serpapi.com/search.json?engine=google_ai_overview&page_token=Oy9lAXicxZbbkqo4FIbv5z2Gm70RbfHUVdRUQNR0i248tK03FMeIgihBI5f7Xeap5mkmoCK2Ys2eqqlJVUgCa2WtJF9-_fmn527Wf_0mLqNoi185jhBSQkGAPLtkBj6n43hjck7g4dBc_oE8YY8ZHOxD03YtwVyGgW8zS0-wN0x8EKqMiYUKY7sClrWh7kwWwGE7pGn-qO2qEVERk04naIaO7RWNdlxhTuPoY_17tU0HJVyyNyXP7MNVfMDqmJReypVWacjpPjUA_0FBUvIQaQUSgI8sZBW0SaG_TB0RbQPay14lXTFnBIGY2NAqqSrtSKhgNhGmk0ldMXHXGouDCpTC2PAaM_Gdp-vpgHmaA4RAund5GFi6PFGxzdXuNmHQOffa6JldmihdenaGUxoHic3Lp2QqcnZWs_FMvu7kGz2FoSL2JMgX5QfACIA5acdqExYu4lS2ZDe_xDUAARJnIUpYmTNC2lQ411yaaSfECXjSpFUOuvNgfAhG86b3MfX5rmg02PpQn3db2FA506B2XqBbtqUttfL3FHETZ4zjPONIt9RpQxTL8brUL4mVHODJ3sGbI0ighOqjRcinzZPzlgVFVE8OIp1JzRlKqAxMAPok2WRaKeldelDoJl46uAP8UtC1odU9v51e_MAtpOB0MnJ2P9At4CjXEiCjDBgIbi6hfLtaeZzgjtJYUhb5HB1J78mbdwCWly85huTcTU3uAEzMMobFrNteZ6mgNHuaEUmSkt5oTQKrqTE87fVUBDd5pOvJnesMiM3eiyyD-_LwsG9KoYBkBV1I_gJmHuiO5QTvreVeYvvaXISrKvsZrtk6a5UtcgY48I1fUGnz_0H8rOFqouEyfIi4-gxxquHqUw1HIK_h7lnDixCH8IuGkyeIQ3mdQ_z4RMMzxNE_QBwVIS49Qrxzj7hbgPgo0fAr4giNvmh4uvZTdjnEf13Dx_9Gw1Pi7VNzK-j7FSoU9t5g486crW_ZBPBRXNlO2NYnb8Wzqovuhd3xo1fd8r5rrvUqvrxFscXsBAC_uZvI9jzbjPa6920bBls7jGLG98JAKOt1KdjVXVIDx27tTd37IGQXg-Zmp7RMSTvsaofjuBW6x-060nv8kJR3Sl8zJvCt3qvLoYJ_DNjJqNVxDA_5-_aRNN4_FHT4GChDjx_GH2TRgT3Fma9fxGlbsbpNe2GMzYE62Q_9xXiizN2uV2eN1sFbkfBTqqRZYcFheQcYcvdoA8bXLWzT_25-aAqUBh6BgQpmKPlxYLCpazY-CHyzajhOw7CbtZpj2TzjoyjeCnyFwZtQqPwN5lT1Kw'},
   'organic_results': [{'position': 1,
     'title': 'Generative AI: Navigating intellectual property',
     'link': 'https://www.nixonpeabody.com/insights/articles/2025/09/17/generative-ai-navigating-intellectual-property',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.nixonpeabody.com/insights/articles/2025/09/17/generative-ai-navigating-intellectual-property&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECBoQAQ',
     'displayed_link': 'https://www.nixonpeabody.com › Insights › Articles',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLPnTOO5M7XixSybRoELvVqM.png',
     'date': 'Sep 17, 2025',
     'snippet': "Fully AI-generated content is ineligible for copyright registration in the US, as human authorship is required. The US Copyright Office's March ...",
     'snippet_highlighted_words': ['Fully AI-generated content is ineligible for copyright registration'],
     'about_this_result': {'source': {'description': "Fully AI-generated content is ineligible for copyright registration in the US, as human authorship is required. The US Copyright Office's March ...",
       'source_info_link': 'https://www.nixonpeabody.com/insights/articles/2025/09/17/generative-ai-navigating-intellectual-property',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLON9xneTwJ6p-oEK7v8XHPDbNIYgqLbyvkHbXlnnncIp.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://www.nixonpeabody.com/insights/articles/2025/09/17/generative-ai-navigating-intellectual-property&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.nixonpeabody.com%2Finsights%2Farticles%2F2025%2F09%2F17%2Fgenerative-ai-navigating-intellectual-property',
     'source': 'Nixon Peabody'},
    {'position': 2,
     'title': 'Artificial Intelligence and Intellectual Property',
     'link': 'https://www.wipo.int/en/web/frontier-technologies/artificial-intelligence/index',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.wipo.int/en/web/frontier-technologies/artificial-intelligence/index&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECBgQAQ',
     'displayed_link': 'https://www.wipo.int › web › frontier-technologies › art...',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLFbJ4W4bl3SP4Ta3-cZBZyY.jpeg',
     'snippet': 'AI inventions present the current patent system with a number of challenges. In order to provide better protection and embrace the full value of patents it is ...',
     'snippet_highlighted_words': ['AI inventions present the current patent system with a number of challenges'],
     'about_this_result': {'source': {'description': 'AI inventions present the current patent system with a number of challenges. In order to provide better protection and embrace the full value of patents it is ...',
       'source_info_link': 'https://www.wipo.int/en/web/frontier-technologies/artificial-intelligence/index',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLPY4L76Oy4OLAlRt-rdtRbOckVUvt6BSwv2ZTHJ87DiY.jpeg'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://www.wipo.int/en/web/frontier-technologies/artificial-intelligence/index&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.wipo.int%2Fen%2Fweb%2Ffrontier-technologies%2Fartificial-intelligence%2Findex',
     'source': 'World Intellectual Property Organization (WIPO)'},
    {'position': 3,
     'title': 'AI, Copyright, and the Law: The Ongoing Battle Over ...',
     'link': 'https://sites.usc.edu/iptls/2025/02/04/ai-copyright-and-the-law-the-ongoing-battle-over-intellectual-property-rights/',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://sites.usc.edu/iptls/2025/02/04/ai-copyright-and-the-law-the-ongoing-battle-over-intellectual-property-rights/&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECB0QAQ',
     'displayed_link': 'https://sites.usc.edu › iptls › 2025/02/04 › ai-copyright-...',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLB2QM-AfrP_4C2BRtiVCkt4.png',
     'date': 'Feb 4, 2025',
     'snippet': 'In the past year, courts, legislators, and regulators have grappled with issues such as whether AI-generated content can be copyrighted.',
     'snippet_highlighted_words': ['whether AI-generated content can be copyrighted'],
     'about_this_result': {'source': {'description': 'In the past year, courts, legislators, and regulators have grappled with issues such as whether AI-generated content can be copyrighted.',
       'source_info_link': 'https://sites.usc.edu/iptls/2025/02/04/ai-copyright-and-the-law-the-ongoing-battle-over-intellectual-property-rights/',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLKijlJoj7xUtMDW9GA_EFXVxQwIbm3cwQ4jTulmqD4EY.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://sites.usc.edu/iptls/2025/02/04/ai-copyright-and-the-law-the-ongoing-battle-over-intellectual-property-rights/&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fsites.usc.edu%2Fiptls%2F2025%2F02%2F04%2Fai-copyright-and-the-law-the-ongoing-battle-over-intellectual-property-rights%2F',
     'source': 'University of Southern California'},
    {'position': 4,
     'title': "Copyright Or Copywrong? AI's Intellectual Property ...",
     'link': 'https://www.forbes.com/sites/douglaslaney/2025/02/11/copyright-or-copywrong-ais-intellectual-property-paradox/',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.forbes.com/sites/douglaslaney/2025/02/11/copyright-or-copywrong-ais-intellectual-property-paradox/&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECBwQAQ',
     'displayed_link': 'https://www.forbes.com › Leadership › CIO Network',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLOzvQ1DTrZrICBeX7wA1ATQ.png',
     'date': 'Feb 11, 2025',
     'snippet': 'The report states that AI-generated works need human authorship to obtain copyright protection when significant creative human participation occurs.',
     'snippet_highlighted_words': ['AI-generated works need human authorship'],
     'about_this_result': {'source': {'description': 'The report states that AI-generated works need human authorship to obtain copyright protection when significant creative human participation occurs.',
       'source_info_link': 'https://www.forbes.com/sites/douglaslaney/2025/02/11/copyright-or-copywrong-ais-intellectual-property-paradox/',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLKFKao76TZb6kIZXwlpTqDlzvX3ZpWXHbEl4o-4D2JjY.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://www.forbes.com/sites/douglaslaney/2025/02/11/copyright-or-copywrong-ais-intellectual-property-paradox/&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.forbes.com%2Fsites%2Fdouglaslaney%2F2025%2F02%2F11%2Fcopyright-or-copywrong-ais-intellectual-property-paradox%2F',
     'source': 'Forbes'},
    {'position': 5,
     'title': 'AI and intellectual property rights',
     'link': 'https://www.dentons.com/en/insights/articles/2025/january/28/ai-and-intellectual-property-rights',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.dentons.com/en/insights/articles/2025/january/28/ai-and-intellectual-property-rights&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECBcQAQ',
     'displayed_link': 'https://www.dentons.com › insights › articles › january',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLImqf8hs96Q2SrGsfq5vbYI.png',
     'date': 'Jan 28, 2025',
     'snippet': 'AI tools are now increasingly being used for searching, reviewing and analysing IP registers, including trademarks, designs and patents for the ...',
     'snippet_highlighted_words': ['AI', 'IP'],
     'about_this_result': {'source': {'description': 'AI tools are now increasingly being used for searching, reviewing and analysing IP registers, including trademarks, designs and patents for the ...',
       'source_info_link': 'https://www.dentons.com/en/insights/articles/2025/january/28/ai-and-intellectual-property-rights',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLMxhmkMt__9YrKrEXD1YwbPoQWEXqOuP3grtKeLiw6Ej.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://www.dentons.com/en/insights/articles/2025/january/28/ai-and-intellectual-property-rights&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.dentons.com%2Fen%2Finsights%2Farticles%2F2025%2Fjanuary%2F28%2Fai-and-intellectual-property-rights',
     'source': 'Dentons'},
    {'position': 6,
     'title': "IP in the Age of AI: What Today's Cases Teach Us About ...",
     'link': 'https://www.americanbar.org/groups/business_law/resources/business-law-today/2025-february/ip-age-of-ai/',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.americanbar.org/groups/business_law/resources/business-law-today/2025-february/ip-age-of-ai/&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECBkQAQ',
     'displayed_link': 'https://www.americanbar.org › resources › 2025-february',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLL8NKcxzwdqAqGgJQR2Ome0.png',
     'date': 'Feb 13, 2025',
     'snippet': 'Copyright and trademark disputes regarding AI-generated material are on the rise—thrusting intellectual property (IP) law into uncharted ...',
     'snippet_highlighted_words': ['Copyright and trademark disputes regarding AI-generated material'],
     'about_this_result': {'source': {'description': 'Copyright and trademark disputes regarding AI-generated material are on the rise—thrusting intellectual property (IP) law into uncharted ...',
       'source_info_link': 'https://www.americanbar.org/groups/business_law/resources/business-law-today/2025-february/ip-age-of-ai/',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLCaUUgTpAinO7hgO3M-6k5Qq6NgaLWhZnCAfuOrJR9sk.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://www.americanbar.org/groups/business_law/resources/business-law-today/2025-february/ip-age-of-ai/&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.americanbar.org%2Fgroups%2Fbusiness_law%2Fresources%2Fbusiness-law-today%2F2025-february%2Fip-age-of-ai%2F',
     'source': 'American Bar Association'},
    {'position': 7,
     'title': 'AI Created It—But Do You Own It? IP Issues Explained',
     'link': 'https://darroweverett.com/ai-and-the-law-who-owns-output-legal-analysis/',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://darroweverett.com/ai-and-the-law-who-owns-output-legal-analysis/&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECBsQAQ',
     'displayed_link': 'https://darroweverett.com › ai-and-the-law-who-owns-o...',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLPgMqhhGII4WI0kipEYciF0.png',
     'date': 'Jul 7, 2025',
     'snippet': 'AI-generated content raises complex legal questions around ownership, copyright, and patents. Learn how businesses can protect their ...',
     'snippet_highlighted_words': ['AI-generated content raises complex legal questions'],
     'about_this_result': {'source': {'description': 'AI-generated content raises complex legal questions around ownership, copyright, and patents. Learn how businesses can protect their ...',
       'source_info_link': 'https://darroweverett.com/ai-and-the-law-who-owns-output-legal-analysis/',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLDtuiMgWrIAg4jJnE3FjDLfXwnXZtH4KRKikcmiwQiTP.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://darroweverett.com/ai-and-the-law-who-owns-output-legal-analysis/&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fdarroweverett.com%2Fai-and-the-law-who-owns-output-legal-analysis%2F',
     'source': 'DarrowEverett LLP'},
    {'position': 8,
     'title': 'Copyright and Artificial Intelligence | U.S. Copyright Office',
     'link': 'https://www.copyright.gov/ai/',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.copyright.gov/ai/&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECDYQAQ',
     'displayed_link': 'https://www.copyright.gov › ai',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLLTgW7cckWIXKgvlJnNTKQQ.png',
     'snippet': 'Copyright and Artificial Intelligence analyzes copyright law and policy issues raised by artificial intelligence.',
     'snippet_highlighted_words': ['Artificial Intelligence',
      'artificial intelligence'],
     'about_this_result': {'source': {'description': 'Copyright and Artificial Intelligence analyzes copyright law and policy issues raised by artificial intelligence.',
       'source_info_link': 'https://www.copyright.gov/ai/',
       'icon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLABa_pxyCsWM7R8Vxw9xpKgNnDO_HtzLWyWkV6ptNN2q.png'},
      'languages': ['en'],
      'regions': ['US']},
     'about_page_link': 'https://www.google.com/search?q=About+https://www.copyright.gov/ai/&tbm=ilp',
     'about_page_serpapi_link': 'https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.copyright.gov%2Fai%2F',
     'source': 'Copyright Office (.gov)'},
    {'position': 9,
     'title': "AI's impact on intellectual property rights and enforcement",
     'link': 'https://gowlingwlg.com/en/insights-resources/articles/2025/ai-impact-ip-rights-enforcement',
     'redirect_link': 'https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://gowlingwlg.com/en/insights-resources/articles/2025/ai-impact-ip-rights-enforcement&ved=2ahUKEwj08b77hM-TAxX_wvACHeZWO4gQFnoECDkQAQ',
     'displayed_link': 'https://gowlingwlg.com › insights-resources › articles › a...',
     'favicon': 'https://serpapi.com/searches/69ce4faf2771430db9186b92/images/Q8dT19U9eFxJknd6XoAbLEYfBRd9l20jVGO5xLuXizk.png',
     'date': 'Aug 28, 2025',
     'snippet': 'From an enforcement standpoint, AI is a powerful tool for detecting infringers and managing IP portfolios. Machine learning systems can monitor ...',
     'snippet_highlighted_words': ['AI is a powerful tool for detecting infringers and managing IP portfolios'],
     'sitelinks': {'inline': [{'title': 'Nancy X. Deng',
        'link': 'https://gowlingwlg.com/en/insights-resources/articles/2025/ai-impact-ip-rights-enforcement#:~:text=Icon-,Nancy%20X.%20Deng'},

---
## 3. Scraping texts from articles and videos

In [21]:
# Define scrapers
def _scrape_url(url: str) -> dict:
    """Scrape clean article text from a URL using Trafilatura."""
    try:
        downloaded = trafilatura.fetch_url(url)
        if not downloaded:
            return {"url": url, "full_text": None,
                    "status": "failed_download"}

        text = trafilatura.extract(
            downloaded,
            include_comments=False,
            include_tables=True,
            no_fallback=False,
            favor_precision=False,
            deduplicate=True
        )
        return {
            "url":       url,
            "full_text": text.strip() if text else None,
            "status":    "success" if text else "failed_extraction"
        }
    except Exception as e:
        return {"url": url, "full_text": None,
                "status": f"error: {str(e)}"}


def _get_youtube_id(url: str) -> str | None:
    """Extract YouTube video ID from URL."""
    patterns = [
        r"youtube\.com/watch\?v=([a-zA-Z0-9_-]{11})",
        r"youtube\.com/shorts/([a-zA-Z0-9_-]{11})",
        r"youtu\.be/([a-zA-Z0-9_-]{11})"
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    return None


def _get_transcript(video_id: str) -> str | None:
    """Fetch YouTube transcript from video ID."""
    try:
        transcript = YouTubeTranscriptApi.get_transcript(
            video_id,
            languages=["en", "en-US", "en-GB"]
        )
        return " ".join([t["text"] for t in transcript])
    except Exception:
        return None


# ═══════════════════════════════════════════════════════
# ENRICHMENT
# ═══════════════════════════════════════════════════════

def enrich_search_results(df: pd.DataFrame,
                         max_workers: int = 5,
                         delay: float = 1.0) -> pd.DataFrame:
    """
    Enrich a DataFrame from collect_search_results() with full text content.
    - Rows with type='article' → scraped via Trafilatura
    - Rows with type='video'   → transcript via YouTube Transcript API

    Args:
        df:          DataFrame returned by collect_articles()
        max_workers: concurrent threads for article scraping
        delay:       seconds between requests per thread

    Returns:
        Enriched DataFrame with added columns:
        - full_text  : scraped article text OR video transcript
        - video_id   : YouTube video ID (videos only)
        - status     : success / failed_download / no_transcript / etc.
    """
    if df.empty:
        print("⚠️  Empty DataFrame — nothing to enrich.")
        return df

    df = df.copy()
    df["full_text"] = None
    df["video_id"]  = None
    df["status"]    = "pending"

    # ── Split by type ──
    article_mask = df["type"] == "article"
    video_mask   = df["type"] == "video"

    article_df = df[article_mask].copy()
    video_df   = df[video_mask].copy()

    # ── Scrape articles ──
    if not article_df.empty:
        print(f"\n📰 Scraping {len(article_df)} articles...")

        url_to_result = {}

        def fetch_with_delay(url):
            time.sleep(delay)
            return _scrape_url(url)

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(fetch_with_delay, row["url"]): idx
                for idx, row in article_df.iterrows()
            }
            for i, future in enumerate(as_completed(futures)):
                result = future.result()
                url_to_result[result["url"]] = result
                icon = "✅" if result["status"] == "success" else "❌"
                source = df.loc[futures[future], "source"] or "Unknown"
                print(f"  {icon} [{i+1}/{len(article_df)}] "
                      f"{source} — {result['status']}")

        # Map results back
        for idx, row in article_df.iterrows():
            r = url_to_result.get(row["url"], {})
            df.at[idx, "full_text"] = r.get("full_text")
            df.at[idx, "status"]    = r.get("status", "unknown")

        success = sum(
            1 for r in url_to_result.values()
            if r["status"] == "success"
        )
        print(f"\n  📊 Articles: {success}/{len(article_df)} "
              f"scraped successfully")

    # ── Fetch video transcripts ──
    if not video_df.empty:
        print(f"\n🎬 Fetching transcripts for "
              f"{len(video_df)} videos...")

        for idx, row in video_df.iterrows():
            url      = row["url"]
            vid_id   = _get_youtube_id(url)
            transcript = None

            if vid_id:
                transcript = _get_transcript(vid_id)

            status = "success" if transcript else "no_transcript"
            icon   = "✅" if transcript else "❌"

            df.at[idx, "video_id"]  = vid_id
            df.at[idx, "full_text"] = transcript
            df.at[idx, "status"]    = status

            title = (row["title"] or "")[:50]
            print(f"  {icon} {title}... [{status}]")

        success = sum(
            1 for idx in video_df.index
            if df.at[idx, "status"] == "success"
        )
        print(f"\n  📊 Videos: {success}/{len(video_df)} "
              f"transcripts fetched")

    return df

In [22]:
# ── Enrich data with full texts from articles and videos ──
df = enrich_search_results(df)

# ── Filter to only successfully scraped content ──
df_clean = df[df["status"] == "success"].reset_index(drop=True)

# ── Inspect results ──
df_clean.head()

📰 Scraping 18 articles...
  ❌ [1/18] Forbes — failed_download
  ❌ [2/18] Dentons — failed_download
  ✅ [3/18] World Intellectual Property Organization (WIPO) — success
  ✅ [4/18] Nixon Peabody — success
  ✅ [5/18] University of Southern California — success
  ❌ [6/18] American Bar Association — failed_download
  ✅ [7/18] DarrowEverett LLP — success
  ✅ [8/18] Copyright Office (.gov) — success
  ✅ [9/18] Gowling WLG — success
  ❌ [10/18] Congress.gov — failed_download
  ✅ [11/18] Ironhack — success
  ✅ [12/18] The Regulatory Review — success
  ✅ [13/18] University of South Florida — success
  ✅ [14/18] Copyright Office (.gov) — success
  ❌ [15/18] RAND — failed_download
  ✅ [16/18] Wikipedia — success
  ✅ [17/18] Yale Law Journal — success
  ✅ [18/18] Association of Research Libraries — success

  📊 Articles: 13/18 scraped successfully

,query,title,snippet,source,date,url,type,full_text,video_id,status
0,AI intellectual property,Generative AI: Navigating intellectual property,Fully AI-generated content is ineligible for c...,Nixon Peabody,"Sep 17, 2025",https://www.nixonpeabody.com/insights/articles...,article,Generative AI is transforming creative and tec...,None,success
1,AI intellectual property,Artificial Intelligence and Intellectual Property,AI inventions present the current patent syste...,World Intellectual Property Organization (WIPO),NaN,https://www.wipo.int/en/web/frontier-technolog...,article,Artificial Intelligence and Intellectual Prope...,None,success
2,AI intellectual property,"AI, Copyright, and the Law: The Ongoing Battle...","In the past year, courts, legislators, and reg...",University of Southern California,"Feb 4, 2025",https://sites.usc.edu/iptls/2025/02/04/ai-copy...,article,By: Negar Bondari\nArtificial intelligence (AI...,None,success
3,AI intellectual property,AI Created It—But Do You Own It? IP Issues Exp...,AI-generated content raises complex legal ques...,DarrowEverett LLP,"Jul 7, 2025",https://darroweverett.com/ai-and-the-law-who-o...,article,Legal Insights\nAs artificial intelligence (AI...,None,success
4,AI intellectual property,Copyright and Artificial Intelligence | U.S. C...,Copyright and Artificial Intelligence analyzes...,Copyright Office (.gov),NaN,https://www.copyright.gov/ai/,article,Copyright and Artificial Intelligence\nSince l...,None,success

In [ ]:
df_clean

In [23]:
df_clean.to_csv("ai_copyright_dataset.csv", index=False)